apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: interesting-mongoose-java-quarkus 
  janus-idp.io/tekton: interesting-mongoose-java-quarkus
  backstage.io/kubernetes-id: interesting-mongoose-java-quarkus
  backstage.io/kubernetes-namespace: flavius-e2e 
  app.kubernetes.io/part-of: interesting-mongoose-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  